### ISSUE TITLE
Sugerencia para facilitar la version local de la web para usuarios windows?

### ISSUE THREAD

**Issue by Ericko1195** [uibcdf/Taller-Linux#20]
Pude activar exitosamente mi ambiente de trabajo con:
`conda activate Taller-Linux`
Pero estuve un buen rato atorado en el comando:
`make html`
Hasta que encontré que para correr esto, primero se tienen que hacer varias cosas según estas instrucciones:
The "make" command is typically used in Unix-like environments and may not be available in Windows by default.
If you're working on a Windows system, you may need to install the necessary tools or dependencies to run the "make" command successfully. One way to do this is by installing the GNU Make for Windows, which provides the "make" command in a Windows environment.
Aún no lo he corroborado, pero si es cierto, entonces sería bueno especificarlo en las intrucciones.

**Comment by dprada** [comment]
Tienes razón!
Es muy posible que eso de un error a usuarios de Windows.
De todas formas, lo que vamos a hacer es quitar esa parte del "make html" en el futuro. Se puso únicamente para que el participante hiciera algo sobre su clon local. Pero podemos pensar en otra cosa.

Cómo usar sphinx para crear webs de documentación se ve en detalle en el taller sobre cómo implementar una librería en Python.

Lo vamos a checar.

Puedes probar por favor a hacer, con el entorno de conda activado:
```bash
conda install make
```
Y si te instala make, prueba el 'make html'.

Si así funciona, entonces se queda. Para corregir esto e incluir a los usuarios de Windows no hará falta modificar la documentación. Únicamente tenemos que incluir 'make' en el fichero 'conda_env.yaml'

Por favor... prueba y dinos si funciona para que tomemos esa solución.

Gracias por el aviso!

**Comment by Ericko1195** [comment]
Volví a crear el ambiente con otro nombre porque tuve algunas confuciones con las intrucciones.
Esta vez creé el ambiente `conda env create -n WEB_Linux -f conda_env.yaml` posicionado en el clon del repositorio 
(base) C:\Users\erick\Taller-Linux
Posterioemente active el ambiente `conda activate WEB_Linux` 
Con el ambiente activado (WEB_Linux) C:\Users\erick\Taller-Linux  ejecuté `make html` y no era reconocido como comando. 
Por último intenté `conda install make`
pero obtuve error:
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - make

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org/

and use the search bar at the top of the page.

**Comment by dprada** [comment]
Y si le dices que lo descargue de 'conda-forge'?
```bash
conda install -c conda-forge make
```
Es buena idea tener 'conda-forge' en los canales por defecto:
```bash
conda config --add channels conda-forge
```

**Comment by Ericko1195** [comment]
Eso funcionó, pero google-chrome no es reconocido como comando con  `google-chrome _build/html/index.html`
En lugar de eso ejecuté `start _build/html/index.html` en windows power shell y funcionó, se abrió la pagina del taller en google chrome que es mi navegador por default.  
`google-chrome _build/html/index.html` debía ejecutarse en Anaconda promt o window powershell?

**Comment by dprada** [comment]
Estupendo! Podías incluso haber abierto index.html haciendo doble click. Supongo que por defecto se abre con tu navegador habitual.

'google-chrome' está en tu sistema, no está en tu entorno de conda así que no hay por qué recurrer a Anaconda. Como digo, podías hacerlo incluso abriendo la ventana del directorio de tu clon y haciendo doble click. Pero lo que dices es muy relevante, tenemos que corregir eso.


Ahora si quieres puedes por ejemplo abrir con tu editor de textos el fichero 'index.md'. Puedes añadir por ejemplo un párrafo de texto... probar la sintaxis de Markdown para hacer una sección nueva y poner por ejemplo una tabla:

```markdown
| A | B | C |
|---|---|---|
| 0.1 | 2 | 10 |
| 0.2 | 4 | 20 |
| 0.3 | 6 | 30 |
```

Guardas el fichero y haces en la terminal:
```bash
make clean
make html
```
Esto borrará las páginas html compiladas anteriormente y generará unas nuevas.
Al abrir con tu navegador de  nuevo el fichero '_build/html/index.html' debes ver tus modificaciones!

**Comment by dprada** [comment]
Gracias por indicar estos defectos en las explicaciones para Windows. Nos queda claro como solucionarlo. Hay que añadir 'make' en el fichero 'conda-env.yaml' y aclarar que en Windows no funcional el comando con 'google-chrome'.

Ahora, si consideras que este hilo ha sido resuelto puedes cerrarlo. No se perderá... queda almacenado con el status "closed" y puede ser consultado o reabierto en el futuro.

Para cerrarlo usa el botón de abajo a la derecha que dice "Close with comment".

Muchas gracias de nuevo!!! 😃 👍🏻
Ha sido un buen ejemplo de cómo se trabaja en colaboración usando GitHub. Esto mismo que has hecho, es lo que nosotros hacemos con las herramientas que usamos y sus desarrolladores. 🤓 👍🏻

**Comment by LMMV** [comment]
@Ericko1195 enhorabuena!! sin proponértelo les has mostrado a los participantes del taller cómo se trabaja en colaboración usando GitHub... 

Como pudiste experimentar, compartir es mejor que competir a la hora de resolver un problema; y buscar soluciones en los distintos foros te hizo tener una experiencia de inmersión en la forma de trabajar de muchos investigadores en el mundo . Me alegro un montón! Deseo que esta forma de trabajar impacte positivamente en tu formación de posgrado...

Gracias!!
