### ISSUE TITLE
Sobre crea un ambiente para trabajar en el taller help wanted

### ISSUE THREAD

**Issue by mtussi01** [uibcdf/Taller-Linux#6]
No sé cómo usar el fichero «conda_env.yaml» para crear un ambiente para trabajar en el taller!

Ni como crear mi versión local de la web del taller:
En el mismo directorio de tu clon local de este repositorio (¿dónde exactamente?), ejecuta: 
make html

**Comment by dprada** [comment]
Hola @mtussi01:
Tienes razón en que la documentación no es del todo clara a este respecto. Vamos a hacer las correcciones adecuadas. Te volvemos a escribir pronto.

**Comment by LMMV** [comment]
Listo!!

**Comment by mtussi01** [comment]
Sigo sin saber como crear un ambiente de trabajo haciendo uso de las mismas herramientas que los desarrolladores y el resto de participantes utilizando el fichero «conda_env.yaml» ni cómo crear mi "copia de la web del Taller-Lynux"

(base) 192:~ user$ conda info --envs
# conda environments:
#
base                  *  /Applications/anaconda3
Taller-Lynux             /Applications/anaconda3/envs/Taller-Lynux
academia                 /Applications/anaconda3/envs/academia

(base) 192:~ user$ conda activate Taller-Lynux
(Taller-Lynux) 192:~ user$

**Comment by dprada** [comment]
Hola! Estamos trabajando en instrucciones claras para todos, pero no vamos todo lo rápido que nos gustaría. Vamos en paralelo a intentar echarte una mano:

Vemos que instalaste conda. Y que has creado un ambiente llamado "Taller-Lynux."

Para crear el ambiente con la receta que ya hay en un fichero '*.yaml' debemos ejecutar en el mismo directorio donde está el fichero '*.yaml':
```bash
conda env create -n Taller-Linux -f conda_env.yaml
```

Una vez creado puedes activarlo y comprobar que los paquetes que se describen en el fichero 'conda_env.yaml' están instalados. El comando `conda list` te arroja la lista de paquetes instalados en el ambiente activo:
```bash
conda activate Taller-Linux
conda list
```

Deberías encontrar allí todos estos paquetes (además de otros):
```
- python=3.10
- mamba
- jupyterlab
- sphinx
- sphinx-book-theme
- sphinxcontrib-bibtex
- sphinx-copybutton
- sphinx-design
- sphinx-favicon
- myst-nb
```

Ahora, eso lo podrás llevar a cabo adecuadamente si tienes en tu compu un clon local de tu fork. Y ya hemos visto que efectivamente [si lo tienes](https://github.com/mtussi01/Taller-Linux).

Comprueba en primer lugar que en tu computadora tienes `git` instalado... y a ser posible instala programa 'gh' (conveniente, pero no necesario).

Puedes decirnos si tienes `git` instalado (estamos preparando documentación de esto también)? Si está instalado, el siguiente comando en la terminal debería de arrojar la versión que tienes:
```bash
git --version
```

Estamos al pendiente. Ánimo! 💪🏻

**Comment by mtussi01** [comment]
Ufff!!!
The HTML pages are in _build/html

Pero ahora NO tengo un sistema operativo Linux (tengo MacOS 10.15.7) y uso Safari  :)) aí que no puedo ver la copia de la página web

**Comment by dprada** [comment]
Tienes que poder. 😄 
No creo que sea estríctamente necesario hacerlo por terminal.

Con el entorno gráfico de ventanas ubícate en el directorio 'html' que está en 'build'. Abre el fichero 'index.html' con el ratón. Debería dispararse Safari para ver el contenido de ese fichero en tu navegador.

Supongo que en la terminal de un macOS también sirve una de estas opciones:
```bash
open _build/html/index.html
```
o

```bash
open -a Safari _build/html/index.html
```

**Comment by mtussi01** [comment]
HURRA!!!! :)))
Ambos comandos funcionaron desde la terminal!
GRACIAS!

**Comment by mtussi01** [comment]
Aunque no supe a qué te referías con esto:
"Con el entorno gráfico de ventanas **ubícate en el directorio 'html' que está en '_build'.** Abre el fichero 'index.html' con el ratón". Debería dispararse Safari para ver el contenido de ese fichero en tu navegador.

**Comment by dprada** [comment]
Genial!

Ahora si quieres puedes por ejemplo abrir con tu editor de textos el fichero 'index.md'. Puedes añadir por ejemplo un párrafo de texto... probar la sintaxis de Markdown para hacer una sección nueva y poner por ejemplo una tabla:

```markdown
| A | B | C |
|---|---|---|
| 0.1 | 2 | 10 |
| 0.2 | 4 | 20 |
| 0.3 | 6 | 30 |
```

Guardas el fichero haces en la terminal:
```bash
make clean
make html
```
Esto borrará las páginas html compiladas anteriormente y generará unas nuevas.
Al abrir con Safari el fichero 'index.html' debes ver tus modificaciones!

Por último, si consideras que el problema de este issue ha sido resuelto, puedes cerrarlo (el botón de abajo que dice "Close with comment"). Eso no quiere decir que quede borrado. Se almacena con el estatus de "cerrado" y puede ser consultado y/o reabierto en el futuro -en cualquier momento-.

Enhorabuena!!!! Resolviste el reto de la semana 1!!!! 🥇

**Comment by dprada** [comment]
> Aunque no supe a qué te referías con esto: "Con el entorno gráfico de ventanas **ubícate en el directorio 'html' que está en '_build'.** Abre el fichero 'index.html' con el ratón". Debería dispararse Safari para ver el contenido de ese fichero en tu navegador.

Me refería a que sin la terminal abrieras con el ratón el fichero 'index.html'.

**Comment by mtussi01** [comment]
> Genial!
> 
> Ahora si quieres puedes por ejemplo abrir con tu editor de textos el fichero 'index.md'. Puedes añadir por ejemplo un párrafo de texto... probar la sintaxis de Markdown para hacer una sección nueva y poner por ejemplo una tabla:
> 
> ```gfm
> | A | B | C |
> |---|---|---|
> | 0.1 | 2 | 10 |
> | 0.2 | 4 | 20 |
> | 0.3 | 6 | 30 |
> ```
> 
> Guardas el fichero y haces en la terminal:
> 
> ```shell
> make clean
> make html
> ```
> 
> Esto borrará las páginas html compiladas anteriormente y generará unas nuevas. Al abrir con Safari el fichero 'index.html' debes ver tus modificaciones!
> 
> Por último, si consideras que el problema de este issue ha sido resuelto, puedes cerrarlo (el botón de abajo que dice "Close with comment"). Eso no quiere decir que quede borrado. Se almacena con el estatus de "cerrado" y puede ser consultado y/o reabierto en el futuro -en cualquier momento-.
> 
> Enhorabuena!!!! Resolviste el reto de la semana 1!!!! 🥇

Ya lo hice!!! Gracias! :)))
